ARG BASE_CONTAINER=jupyter/minimal-notebook
FROM $BASE_CONTAINER

USER root
RUN pip install numpy matplotlib plotly

ENV PROJECT_DIR /home/jovyan/csd
WORKDIR ${PROJECT_DIR}
ADD requirements.txt .
RUN pip install -r requirements.txt
COPY . .
RUN pip install -e .

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID
CMD ["jupyter", "notebook", "--no-browser", "--ip=0.0.0.0", "--port=9999"]
