import strawberryfields as sf
import numpy as np
import tensorflow as tf
import os
from loguru import logger

# Hides info messages from TensorFlow.
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Number of layers of the Dolinar receiver. Selecting 4 as the most basic,
# non-trivial case.
NUM_LAYERS = 4

# Number of quantum modes. Basic 2-mode case.
NUM_MODES = 2

# Number of variables being optimized per mode.
NUM_VARIABLES = 1

# Signal amplitude. Default is 1.0.
SIGNAL_AMPLITUDE = 1.0

# Fock backend.
ENGINE = sf.Engine("tf", backend_options={"cutoff_dim": 6})


def generate_nth_layer(layer_number, engine):
    """Generates the nth layer of the Dolinar receiver.
    Given the `layer_number` and `engine` as input, it returns a
    function that generates the necessary quantum circuit for the n-th layer of
    the Dolinar receiver.
    """
    # Reset engine if a program has been executed.
    if engine.run_progs:
        engine.reset()

    # Need k values for the splits of the coherent state.
    amplitudes =  np.ones(NUM_LAYERS) * (SIGNAL_AMPLITUDE / NUM_LAYERS)

    def quantum_layer(input_codeword, displacement_magnitudes_for_each_mode):
        program = sf.Program(NUM_MODES)

        with program.context as q:
            # Prepare the coherent states for the layer. Appropriately scales
            # the amplitudes for each of the layers.
            for m in range(NUM_MODES):
                sf.ops.Coherent(amplitudes[layer_number] * input_codeword[m]) | q[m]

            # Displace each of the modes by using the displacement magnitudes
            # generated by the ML backend.
            for m in range(NUM_MODES):
                sf.Dgate(displacement_magnitudes_for_each_mode[m]) | q[m]

            # Perform measurements.
            sf.ops.MeasureFock() | q

        return engine.run(program)

    return quantum_layer


def build_model(name="predictor"):
    """
    Builds a tensorflow model layer by layer utilising the sequential API.
    """
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(NUM_MODES * NUM_VARIABLES + NUM_LAYERS, ), name="input-layer"),
        tf.keras.layers.Dense(8, activation="relu", name="layer-1"),
        tf.keras.layers.Dense(16, activation="relu", name="layer-2"),
        tf.keras.layers.Dense(NUM_MODES * NUM_VARIABLES, activation="sigmoid", name="output-layer")
    ], name=name)

    return model


def generate_random_codeword():
    """
    Generates a random codeword for `NUM_MODES` modes.
    """
    return np.random.choice([-1, +1], size=NUM_MODES)


def step():
    """
    Runs a single step of optimization for a single value of alpha across all
    layers of the Dolinar receiver.
    """
    global model, layers, optimizer

    previous_predictions = np.random.randn(NUM_MODES * NUM_LAYERS)

    with tf.GradientTape() as tape:
        input_codeword = generate_random_codeword()
        loss = 0

        for nth_layer in range(NUM_LAYERS):
            one_hot_layer_vector = np.zeros(NUM_LAYERS)
            one_hot_layer_vector[nth_layer] = 1
            input_vector = np.hstack((previous_predictions, one_hot_layer_vector))

            predicted_displacements = model(input_vector)
            measurement_of_nth_layer = layers[nth_layer](
                input_codeword,
                2 * SIGNAL_AMPLITUDE * predicted_displacements)


            for kth_mode in range(NUM_MODES):
                if input_codeword[kth_mode] == -1 and measurement_of_nth_layer[kth_mode] < 0:
                    loss += 1

    gradients = tape(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))


if __name__ == '__main__':
    # ML model to predict the displacement magnitude for each of the layers of
    # the Dolinar receiver.
    logger.info("Building model.")
    model = build_model(f"predictor-l-{NUM_LAYERS}-alpha-{SIGNAL_AMPLITUDE}-modes-{NUM_MODES}")
    logger.info("Done.")

    # Layers of the Dolinar receiver.
    logger.info("Building quantum circuits.")
    layers = [generate_nth_layer(n, ENGINE) for n in range(NUM_LAYERS)]
    logger.info("Done.")

    # TODO: Add training loop.

    # Using the Adam optimizer.
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
